language: node_js

node_js:
  - "10"

before_install:
  - export PATH=$PATH:$HOME/.local/bin

install:
  - travis_retry npm install

script:
  - set -e
  - npm run eslint
  - npm run jsinspect
  - npm test

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never

after_success:
  # - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
